#!/usr/bin/env python

import sys
import time
import socket
import random


def run(sock, blocks):
    f = sock.makefile('+w', 0)
    i = 0
    while True:
        msgs = []
        for j in range(blocks):
            msg = 'hello {}\n'.format(random.random())
            f.write(msg)
            msgs.append(msg)
            i += 1
        time.sleep(0.001)
        for j, msg in enumerate(msgs):
            r = f.readline()
            assert r == msg
            print 'OK', i-blocks+j



def main(args=None):
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('host', help='host [(%(default)s]', default='localhost')
    parser.add_argument('-p', help='listening port [(%(default)s]', default=16000, type=int)
    parser.add_argument('-b', help='number of blocks [(%(default)s]', default=10, type=int)
    options = parser.parse_args(args=args)
    port, blocks = options.p, options.b
    s = socket.create_connection((options.host, port))
    try:
        run(s, blocks)
    except KeyboardInterrupt:
        print('Ctrl-C pressed. Bailing out...')
    finally:
        s.close()


if __name__ == '__main__':
    main()
